Repository Hana1Pick/Hana1Pick-Backend, pull requests merged in 2024-06, with the labels that each got.

#3 feat : Swagger 설정 및 예외처리
  build.gradle
  src/main/java/com/hana/hana1pick/domain/test/controller/TestController.java
  src/main/java/com/hana/hana1pick/global/config/BaseException.java
  src/main/java/com/hana/hana1pick/global/config/BaseResponse.java
  src/main/java/com/hana/hana1pick/global/config/BaseResponseStatus.java
  src/main/java/com/hana/hana1pick/global/config/GlobalExceptionHandler.java
  src/main/java/com/hana/hana1pick/global/config/SuccessCode.java
  src/main/java/com/hana/hana1pick/global/config/SwaggerConfig.java
  src/main/resources/application-dev.yml
  src/main/resources/application.yml
Labels: feature

#6 feature/moaclub
  build.gradle
  src/main/java/com/hana/hana1pick/domain/common/entity/Account.java
  src/main/java/com/hana/hana1pick/domain/common/service/AccIdGenerator.java
  src/main/java/com/hana/hana1pick/domain/deposit/repository/DepositRepository.java
  src/main/java/com/hana/hana1pick/domain/moaclub/controller/MoaClubController.java
  src/main/java/com/hana/hana1pick/domain/moaclub/dto/request/OpenMoaClubReqDto.java
  src/main/java/com/hana/hana1pick/domain/moaclub/dto/response/OpenMoaClubResDto.java
  src/main/java/com/hana/hana1pick/domain/moaclub/entity/ClubMembersId.java
  src/main/java/com/hana/hana1pick/domain/moaclub/entity/MoaClub.java
  src/main/java/com/hana/hana1pick/domain/moaclub/entity/MoaClubMembers.java
  src/main/java/com/hana/hana1pick/domain/moaclub/repository/MoaClubMembersRepository.java
  src/main/java/com/hana/hana1pick/domain/moaclub/repository/MoaClubRepository.java
  src/main/java/com/hana/hana1pick/domain/moaclub/service/MoaClubService.java
  src/main/java/com/hana/hana1pick/domain/user/entity/User.java
  src/main/java/com/hana/hana1pick/domain/user/repository/UserRepository.java
  src/main/java/com/hana/hana1pick/global/config/SwaggerConfig.java
  src/main/java/com/hana/hana1pick/global/exception/BaseResponseStatus.java
  src/main/java/com/hana/hana1pick/global/exception/SuccessCode.java
  src/main/java/com/hana/hana1pick/global/security/SecurityConfig.java
Labels: feature

#11 10 feature/create-accounts-view
  src/main/java/com/hana/hana1pick/domain/common/entity/Accounts.java
  src/main/java/com/hana/hana1pick/domain/common/repository/AccountsRepository.java
  src/main/java/com/hana/hana1pick/global/config/WebMvcConfig.java
Labels: feature

#12 feat: accounts 속성 수정
  src/main/java/com/hana/hana1pick/domain/common/entity/Accounts.java
Labels: feature

#14 8 feature/moaclub
  src/main/java/com/hana/hana1pick/Hana1PickApplication.java
  src/main/java/com/hana/hana1pick/domain/common/entity/Account.java
  src/main/java/com/hana/hana1pick/domain/moaclub/controller/MoaClubController.java
  src/main/java/com/hana/hana1pick/domain/moaclub/dto/request/AccIdReqDto.java
  src/main/java/com/hana/hana1pick/domain/moaclub/dto/request/ClubInvitationReqDto.java
  src/main/java/com/hana/hana1pick/domain/moaclub/dto/request/ClubOpeningReqDto.java
  src/main/java/com/hana/hana1pick/domain/moaclub/dto/request/ClubUpdateReqDto.java
  src/main/java/com/hana/hana1pick/domain/moaclub/dto/response/ClubOpeningResDto.java
  src/main/java/com/hana/hana1pick/domain/moaclub/dto/response/ClubResDto.java
  src/main/java/com/hana/hana1pick/domain/moaclub/entity/Currency.java
  src/main/java/com/hana/hana1pick/domain/moaclub/entity/MoaClub.java
  src/main/java/com/hana/hana1pick/domain/moaclub/entity/MoaClubMemberRole.java
  src/main/java/com/hana/hana1pick/domain/moaclub/entity/MoaClubMembers.java
  src/main/java/com/hana/hana1pick/domain/moaclub/entity/MoaClubStatus.java
  src/main/java/com/hana/hana1pick/domain/moaclub/repository/MoaClubMembersRepository.java
  src/main/java/com/hana/hana1pick/domain/moaclub/service/MoaClubService.java
  src/main/java/com/hana/hana1pick/domain/user/controller/UserController.java
  src/main/java/com/hana/hana1pick/domain/user/dto/request/PwCheckReqDto.java
  src/main/java/com/hana/hana1pick/domain/user/dto/response/PwCheckResDto.java
  src/main/java/com/hana/hana1pick/domain/user/entity/User.java
  src/main/java/com/hana/hana1pick/domain/user/entity/UserRankPredict.java
  src/main/java/com/hana/hana1pick/domain/user/repository/UserRepository.java
  src/main/java/com/hana/hana1pick/domain/user/service/UserService.java
  src/main/java/com/hana/hana1pick/global/exception/BaseResponseStatus.java
Labels: refactor, feature

#19 7-feature/cash-out-account
  src/main/java/com/hana/hana1pick/domain/acchistory/entity/AccountHistory.java
  src/main/java/com/hana/hana1pick/domain/acchistory/repository/AccountHistoryRepository.java
  src/main/java/com/hana/hana1pick/domain/acchistory/service/AccountHistoryService.java
  src/main/java/com/hana/hana1pick/domain/celublog/repository/CelublogRepository.java
  src/main/java/com/hana/hana1pick/domain/common/controller/AccountController.java
  src/main/java/com/hana/hana1pick/domain/common/dto/request/AccountForCashOutHisReqDto.java
  src/main/java/com/hana/hana1pick/domain/common/dto/request/AccountForCashOutReqDto.java
  src/main/java/com/hana/hana1pick/domain/common/dto/request/CashOutReqDto.java
  src/main/java/com/hana/hana1pick/domain/common/dto/response/AccountForCashOutHisResDto.java
  src/main/java/com/hana/hana1pick/domain/common/dto/response/AccountForCashOutResDto.java
  src/main/java/com/hana/hana1pick/domain/common/dto/response/AccountHistoryInfoDto.java
  src/main/java/com/hana/hana1pick/domain/common/dto/response/AccountInfoDto.java
  src/main/java/com/hana/hana1pick/domain/common/entity/Account.java
  src/main/java/com/hana/hana1pick/domain/common/entity/Accounts.java
  src/main/java/com/hana/hana1pick/domain/common/repository/AccountsRepository.java
  src/main/java/com/hana/hana1pick/domain/common/service/AccountService.java
  src/main/java/com/hana/hana1pick/domain/deposit/repository/DepositRepository.java
  src/main/java/com/hana/hana1pick/domain/moaclub/repository/MoaClubRepository.java
  src/main/java/com/hana/hana1pick/global/exception/BaseResponseStatus.java
Labels: feature

#22 9 feature/moaclub etc
  build.gradle
  src/main/java/com/hana/hana1pick/Hana1PickApplication.java
  src/main/java/com/hana/hana1pick/domain/acchistory/repository/AccHistoryRepository.java
  src/main/java/com/hana/hana1pick/domain/acchistory/repository/AccountHistoryRepository.java
  src/main/java/com/hana/hana1pick/domain/acchistory/service/AccHistoryService.java
  src/main/java/com/hana/hana1pick/domain/acchistory/service/AccountHistoryService.java
  src/main/java/com/hana/hana1pick/domain/autotranfer/entity/AutoTransfer.java
  src/main/java/com/hana/hana1pick/domain/autotranfer/entity/AutoTransferId.java
  src/main/java/com/hana/hana1pick/domain/autotranfer/repository/AutoTransferRepository.java
  src/main/java/com/hana/hana1pick/domain/autotranfer/service/AutoTransferService.java
  src/main/java/com/hana/hana1pick/domain/common/dto/request/CashOutReqDto.java
  src/main/java/com/hana/hana1pick/domain/common/entity/Account.java
  src/main/java/com/hana/hana1pick/domain/common/repository/AccountsRepository.java
  src/main/java/com/hana/hana1pick/domain/common/service/AccountService.java
  src/main/java/com/hana/hana1pick/domain/deposit/entity/Deposit.java
  src/main/java/com/hana/hana1pick/domain/moaclub/controller/MoaClubController.java
  src/main/java/com/hana/hana1pick/domain/moaclub/dto/request/ClubAutoTransferReqDto.java
  src/main/java/com/hana/hana1pick/domain/moaclub/dto/request/ClubFeeStatusReqDto.java
  src/main/java/com/hana/hana1pick/domain/moaclub/dto/request/ClubManagerChangeReqDto.java
  src/main/java/com/hana/hana1pick/domain/moaclub/dto/request/ClubMemberLeaveReqDto.java
  src/main/java/com/hana/hana1pick/domain/moaclub/dto/request/ClubVoteReqDto.java
  src/main/java/com/hana/hana1pick/domain/moaclub/dto/request/ClubWithdrawReqDto.java
  src/main/java/com/hana/hana1pick/domain/moaclub/dto/response/ClubFeeStatusResDto.java
  src/main/java/com/hana/hana1pick/domain/moaclub/dto/response/ClubResDto.java
  src/main/java/com/hana/hana1pick/domain/moaclub/dto/response/ManagerChangeReq.java
  src/main/java/com/hana/hana1pick/domain/moaclub/dto/response/VoteResult.java
  src/main/java/com/hana/hana1pick/domain/moaclub/dto/response/WithdrawReq.java
  src/main/java/com/hana/hana1pick/domain/moaclub/entity/MoaClubMemberRole.java
  src/main/java/com/hana/hana1pick/domain/moaclub/entity/MoaClubMembers.java
  src/main/java/com/hana/hana1pick/domain/moaclub/repository/MoaClubMembersRepository.java
  src/main/java/com/hana/hana1pick/domain/moaclub/service/ManagerChangeListener.java
  src/main/java/com/hana/hana1pick/domain/moaclub/service/MoaClubService.java
  src/main/java/com/hana/hana1pick/domain/moaclub/service/WithdrawListener.java
  src/main/java/com/hana/hana1pick/domain/user/entity/UserTrsfLimit.java
  src/main/java/com/hana/hana1pick/domain/user/repository/UserTrsfLimitRepository.java
  src/main/java/com/hana/hana1pick/domain/user/service/UserTrsfLimitService.java
  src/main/java/com/hana/hana1pick/global/config/RedisConfig.java
  src/main/java/com/hana/hana1pick/global/exception/BaseResponseStatus.java
  src/main/java/com/hana/hana1pick/global/scheduler/Hana1PickScheduler.java
Labels: feature

#24 23 feature/moaclub autotransfer
  src/main/java/com/hana/hana1pick/domain/acchistory/repository/AccHistoryRepository.java
  src/main/java/com/hana/hana1pick/domain/autotranfer/repository/AutoTransferRepository.java
  src/main/java/com/hana/hana1pick/domain/autotranfer/service/AutoTransferService.java
  src/main/java/com/hana/hana1pick/domain/moaclub/controller/MoaClubController.java
  src/main/java/com/hana/hana1pick/domain/moaclub/service/MoaClubService.java
  src/main/java/com/hana/hana1pick/global/exception/BaseResponseStatus.java
Labels: bug, feature

#21 18 feature/kakao login
  build.gradle
  src/main/java/com/hana/hana1pick/domain/user/controller/UserController.java
  src/main/java/com/hana/hana1pick/domain/user/dto/response/UserInfoResDto.java
  src/main/java/com/hana/hana1pick/domain/user/entity/User.java
  src/main/java/com/hana/hana1pick/domain/user/repository/UserRepository.java
  src/main/java/com/hana/hana1pick/domain/user/service/KakaoService.java
  src/main/java/com/hana/hana1pick/domain/user/service/UserService.java
  src/main/java/com/hana/hana1pick/global/exception/BaseResponseStatus.java
  src/main/resources/application-dev.yml
  src/main/resources/static/favicon.ico
Labels: feature

#27 26 feature/account list
  src/main/java/com/hana/hana1pick/domain/common/dto/response/AccountResDto.java
  src/main/java/com/hana/hana1pick/domain/common/entity/Accounts.java
  src/main/java/com/hana/hana1pick/domain/common/repository/AccountsRepository.java
  src/main/java/com/hana/hana1pick/domain/user/controller/UserController.java
  src/main/java/com/hana/hana1pick/domain/user/service/UserService.java
  src/main/java/com/hana/hana1pick/global/exception/BaseResponseStatus.java
Labels: feature

#28 20 feature/celub account list
  src/main/java/com/hana/hana1pick/domain/acchistory/repository/AccHistoryRepository.java
  src/main/java/com/hana/hana1pick/domain/celublog/controller/CelublogController.java
  src/main/java/com/hana/hana1pick/domain/celublog/dto/request/AccListReqDto.java
  src/main/java/com/hana/hana1pick/domain/celublog/dto/response/AccDetailResDto.java
  src/main/java/com/hana/hana1pick/domain/celublog/dto/response/AccListResDto.java
  src/main/java/com/hana/hana1pick/domain/celublog/repository/CelublogRepository.java
  src/main/java/com/hana/hana1pick/domain/celublog/repository/RulesRepository.java
  src/main/java/com/hana/hana1pick/domain/celublog/service/CelublogService.java
  src/main/java/com/hana/hana1pick/global/exception/BaseResponseStatus.java
Labels: feature

#35 feature/create-deposit
  src/main/java/com/hana/hana1pick/domain/deposit/dto/request/DepositCreateReqDto.java
  src/main/java/com/hana/hana1pick/domain/deposit/dto/response/DepositCreateResDto.java
  src/main/java/com/hana/hana1pick/domain/deposit/entity/Deposit.java
  src/main/java/com/hana/hana1pick/domain/deposit/service/DepositService.java
  src/main/java/com/hana/hana1pick/domain/test/controller/TestController.java
  src/main/java/com/hana/hana1pick/domain/user/controller/UserController.java
  src/main/java/com/hana/hana1pick/domain/user/dto/request/UserUpdateReqDto.java
  src/main/java/com/hana/hana1pick/domain/user/dto/response/UserCreateResDto.java
  src/main/java/com/hana/hana1pick/domain/user/entity/User.java
  src/main/java/com/hana/hana1pick/domain/user/repository/UserRepository.java
  src/main/java/com/hana/hana1pick/domain/user/service/UserService.java
  src/main/java/com/hana/hana1pick/global/exception/BaseResponseStatus.java
Labels: feature

#36 18 feature/kakao login
  src/main/java/com/hana/hana1pick/domain/user/controller/UserController.java
  src/main/java/com/hana/hana1pick/domain/user/dto/response/UserInfoResDto.java
  src/main/java/com/hana/hana1pick/domain/user/service/KakaoService.java
  src/main/java/com/hana/hana1pick/domain/user/service/UserService.java
  src/main/java/com/hana/hana1pick/global/exception/BaseResponseStatus.java
Labels: refactor, feature

#38 37-refactor/login-deposit
  src/main/java/com/hana/hana1pick/domain/user/controller/UserController.java
  src/main/java/com/hana/hana1pick/domain/user/entity/User.java
  src/main/java/com/hana/hana1pick/domain/user/service/UserService.java
Labels: refactor

#40 39 feature/create depositaccount
  src/main/java/com/hana/hana1pick/domain/common/entity/Account.java
  src/main/java/com/hana/hana1pick/domain/deposit/controller/DepositController.java
  src/main/java/com/hana/hana1pick/domain/deposit/dto/request/DepositCreateReqDto.java
  src/main/java/com/hana/hana1pick/domain/deposit/entity/Deposit.java
  src/main/java/com/hana/hana1pick/domain/deposit/service/DepositService.java
  src/main/java/com/hana/hana1pick/domain/test/controller/TestController.java
  src/main/java/com/hana/hana1pick/domain/user/controller/UserController.java
  src/main/java/com/hana/hana1pick/domain/user/dto/response/UserCreateResDto.java
  src/main/java/com/hana/hana1pick/domain/user/repository/UserRepository.java
  src/main/java/com/hana/hana1pick/domain/user/service/UserService.java
  src/main/java/com/hana/hana1pick/global/exception/BaseResponseStatus.java
Labels: feature

#42 41-feature/handle-qr-transfer
  src/main/java/com/hana/hana1pick/domain/acchistory/controller/AccHistoryController.java
  src/main/java/com/hana/hana1pick/domain/acchistory/dto/response/AccHistoryForQrResDto.java
  src/main/java/com/hana/hana1pick/domain/acchistory/repository/AccHistoryRepository.java
  src/main/java/com/hana/hana1pick/domain/acchistory/service/AccHistoryService.java
  src/main/java/com/hana/hana1pick/global/exception/BaseResponseStatus.java
Labels: feature

#45 43-feature/handle-transfer-limit
  src/main/java/com/hana/hana1pick/domain/common/dto/request/CashOutReqDto.java
  src/main/java/com/hana/hana1pick/domain/common/service/AccountService.java
  src/main/java/com/hana/hana1pick/global/exception/BaseResponseStatus.java
Labels: feature

#48 47-bug/handle-ci-cd
  .gitignore
  src/main/java/com/hana/hana1pick/global/config/JasyptConfig.java
  src/main/resources/application-dev.yml
Labels: bug

#49 refactor: ENTRYPOINT 수정
  Dockerfile
Labels: bug

#50 47-bug/handle-ci-cd
  scripts/deploy.sh
Labels: bug
